name: API Rest tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Install ServeRest
        run: npm i serverest
        
      - name: Run ServeRest
        run: (npx serverest@latest &)
        
      - name: Cypress run
        uses: cypress-io/github-action@v2
